### ISSUE TITLE
Pry.config.prompt is deprecated

### ISSUE THREAD

**Issue by a2ikm** [arches/marco-polo#17]
`Pry.config.prompt` used [here](https://github.com/arches/marco-polo/blob/a8180458608718059f7c83fd778a776cc9f3a0c6/lib/marco-polo.rb#L15) is deprecated since pry 0.13.0.
https://github.com/pry/pry/blob/5805952cf32f320508df6a5ba4f768b9f4394805/CHANGELOG.md?plain=1#L114-L120

pry with marco-polo now prints the following warning:
```
warning: setting prompt with help of `Pry.config.prompt = [proc {}, proc {}]` is deprecated. Use Pry::Prompt API instead
```

**Comment by sakuro** [comment]
I'd submitted a PR for that https://github.com/arches/marco-polo/pull/16 but this repo seems inactive for years 🤷🏽
